language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
deploy:
  provider: heroku
  app: ophio-foodly
  api_key:
    secure: j+gFkaV9bPn+ZXp9d2U+rRuxVPlLNJsjdSXHg6fP+5o+Y7II/R1BdO1MAvv8IRsFuiUQ7QLw7/2BON3d6l4fUbLcRB6tkUxuobkGOLz9lQVfguSnqLNBhvDIGR2w4OLfVEf6L/14Ti8mVHiRx+G65QEepuZVMq/kBR7Lod7Bm00=
